routes/web.php
<?php


use App\Http\Controllers\DemoController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginRegisterController;

use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
/*
Route::get('/{nom}', function($n){
    Return "Bonjour <strong>$n</strong>";
});*/
Route::get('/', [HomeController::class, 'home'])->name('home');

Route::prefix('admin')->group(function(){
    Route::resource("categories", CategoryController::class)
                                    ->except(['show'])
                                    ->names('categories');

    Route::resource("products", ProductController::class)->names("products");
});


Route::get('/demo/{id}',[DemoController::class, "voir"])->name("demo");
Route::get("about",[DemoController::class, "about"])->name('about');
Route::controller(LoginRegisterController::class)->group(function(){
    Route::get('/register', 'register')->name('register');
    Route::post('/register', 'userStore')->name('userStore');
    Route::get('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/login', 'login')->name('login');
    Route::post('/login', 'authenticate')->name('authenticate');
    Route::get('/logout', 'logout')->name('logout');
});

resources/views/partials/footer.blade.php
<div class="b-example-divider"></div>

<footer class="py-5 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary fw-bold">&copy; 2023 CISSE410, Inc</p>
</footer>

resources/views/partials/header.blade.php
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ route('home') }}">LGI Commerce</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Administration
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ route('categories.index') }}">Gestion des catégories</a></li>
                    <li><a class="dropdown-item" href="{{ route('products.index') }}">Gestion des produits</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Tableau de bord</a></li>
                </ul>
            </li>
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            {{-- <button class="btn btn-outline-success" type="submit">Search</button> --}}
        </form>
        {{-- <div class="d-grid gap-2 d-md-block">
            <a href="{{ route('login') }}" class="btn btn-primary" type="button">Log In</a>
            <a href="{{ route('register') }}" class="btn btn-primary active" type="button">Register</a>
        </div> --}}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            @guest
                <a href="{{ route('login') }}" class="btn btn-primary" type="button">Se connecter</a>
                @else
                <form class="d-flex" action="{{ route('logout') }}" method="get">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-danger">Se deconnecter</button>
                </form>
            @endguest
        </div>
      </div>
    </div>
  </nav>